# Generated by Django 4.0.4 on 2022-04-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game Title')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=255, verbose_name='UserName in Bot')),
                ('game', models.CharField(max_length=255, verbose_name='Favorite Game')),
                ('about', models.TextField(verbose_name='Personal Info')),
                ('search_game', models.CharField(max_length=255, verbose_name='Game for search')),
                ('is_search', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
