# Generated by Django 4.0.4 on 2022-04-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Game Title'),
        ),
        migrations.AlterField(
            model_name='users',
            name='game',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='Bot.games', to_field='title', verbose_name='Favorite Game'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tg_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
