# Generated by Django 4.0.4 on 2022-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_alter_games_title_alter_users_game_alter_users_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='game',
            field=models.CharField(max_length=255, verbose_name='Favorite Game'),
        ),
    ]
